- hosts: etcd
  become: yes
  roles:
  - role: etcd

- hosts: patroni1
  become: yes
  roles:
  - { role: postgresql, postgres_service_enabled: no }
  - role: pghoard

- hosts: patroni
  become: yes
  roles:
  - role: docker-io
  - role: patroni
